name: Deploy to Namecheap

on:
  push:
    branches:
      - main  # Or 'master', depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          # Private key for SSH authentication
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host to connect to
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          # Remote user
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          # Remote port
          REMOTE_PORT: 22
          # The local directory to copy from, "." for the entire repository
          SOURCE: "."
          # The destination directory on the remote server
          TARGET: "public_html/"
