name: Deploy to Namecheap via SFTP

on:
  push:
    branches:
      - main  # Or 'master', depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: laryxb/beagle-sftp-action@v2.0.4
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22 # SFTP usually runs on port 22
          remote_path: public_html/
